### ISSUE TITLE
Trails are broken when resizing a window

### ISSUE THREAD

**Issue by sppmacd** [Adam-Ratajczak/2d-solar-system-simulator#1]
Reproduce:
* Run a simulation for a while
* Resize a window
* Observe bugs

![image](https://user-images.githubusercontent.com/42967349/160856334-0190768a-bb2f-4f8f-bc9e-91bfb1b4f521.png)

**Comment by sppmacd** [comment]
They were never fixed... and now broken by 3D update...

**Comment by Adam-Ratajczak** [comment]
I think it's time to close this issue.

**Comment by sppmacd** [comment]
:)

**Comment by sppmacd** [comment]
also you can say "Closes #ISSUE" or "Fixes #ISSUE" in commit message and it should close automatically.
