### ISSUE TITLE
History (?): Is very RAM-heavy

### ISSUE THREAD

**Issue by sppmacd** [Adam-Ratajczak/2d-solar-system-simulator#5]
Probably very much related to sanitizers, but when you do many (e.g 1000) iterations per second, RAM usage goes by ~30 MB every second.
![image](https://user-images.githubusercontent.com/42967349/163712684-a2af4b11-6eaf-4a56-b0fe-b6ae0049c8f2.png)

**Comment by Adam-Ratajczak** [comment]
I know, our CPU usage is also quite high

**Comment by Adam-Ratajczak** [comment]
Integrals are our only hope.

**Comment by sppmacd** [comment]
we can limit history for now

**Comment by Adam-Ratajczak** [comment]
Do it if u want

**Comment by Adam-Ratajczak** [comment]
![image](https://user-images.githubusercontent.com/99399261/164996565-6626c586-737b-4e01-9ff1-9b281f887ee5.png)
I think this issue is solved for now. There is only the performance problem. But we can add some approximations to the simulation in the future.

**Comment by Adam-Ratajczak** [comment]
btw optimization halves the CPU usage
